version: "3"

services:
  openfire:
    image: gidiyan/ci-openfire:v.0.0.3
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "5222:5222"
      - "5269:5269"
      - "5223:5223"
      - "7443:7443"
      - "7777:7777"
      - "7070:7070"
      - "5229:5229"
      - "5275:5275"
    links:
      - db:db
  db:
    container_name: postgres
    image: postgres:11.15-alpine.0.0.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
