version: "2.2"

services:
  openfire:
    image: openfire:v.0.0.1
    ports:
      - "9090:9090"
      - "5222:5222"
      - "5269:5269"
      - "5223:5223"
      - "7443:7443"
      - "7777:7777"
      - "7070:7070"
      - "5229:5229"
      - "5275:5275"
    volumes:
      - data1:/var/lib/openfire
    links:
      - db:db
  db:
    container_name: postgres
    image: postgres:11.14-alpine
    command: -c ssl=off  
    ports:
      - "5432:5432"
    volumes:
      - data2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret

volumes:
  data1:
    external: true
    name: openfire_data
  data2:
    external: true
    name: data
